### ISSUE TITLE
Client – functionality to retrieve current balance (client check server)

### ISSUE THREAD

**Issue by EstifanosG** [COMP231-S62G1/FoodOrderSystem062Sec62G1#129]
#121

**Comment by wooseung-sim** [comment]
Server side interface is still needed to finish this story

**Comment by wooseung-sim** [comment]
Guide for server side devleper
Server interface file name to retrieve balance amount should be "getBalance.php"
and return type is CommonModel object and return remaining balance amount as result attribute in the object.
